name: tvg-ui
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]
  workflow_dispatch:

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  build_stg:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    environment: stg
    env:
      adclientid: "${{ secrets.adclientid }}"
      adtenantid: "${{ secrets.adtenantid }}"
      publicvapidkey: "${{ secrets.publicvapidkey }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup nodejs
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "16.x"

      - name: cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ github.workflow }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.workflow }}-${{ secrets.CACHE_VERSION }}-

      - name: npm install
        run: npm ci

      - name: replace secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./src/index.html"]'

      - name: npm build
        run: npm run build

      - name: upload ui artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist_ui
          path: ./dist/tvg-ui

      - name: upload api artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist_api
          path: ./api

  build_prod:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    environment: prod
    env:
      adclientid: "${{ secrets.adclientid }}"
      adtenantid: "${{ secrets.adtenantid }}"
      publicvapidkey: "${{ secrets.publicvapidkey }}"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup nodejs
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "16.x"

      - name: cache node_modules
        uses: actions/cache@v2
        id: cache-nodemodules
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ github.workflow }}-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.workflow }}-${{ secrets.CACHE_VERSION }}-

      - name: npm install
        run: npm ci

      - name: replace secrets
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["./src/index.html"]'

      - name: npm build
        run: npm run build

      - name: upload ui artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist_ui
          path: ./dist/tvg-ui

      - name: upload api artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist_api
          path: ./api

  deploy_stg_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [build_stg]
    environment: stg
    name: deploy stg westeurope
    steps:
      - name: download ui artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_ui"
          path: ./dist

      - name: download api artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_api"
          path: ./api

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN_WESTEUROPE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: "api"
          output_location: ""
          skip_app_build: true

  deploy_prod_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build_prod]
    environment: prod
    name: deploy prod westeurope
    steps:
      - name: download ui artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_ui"
          path: ./dist

      - name: download api artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_api"
          path: ./api

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN_WESTEUROPE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: "api"
          output_location: ""
          skip_app_build: true
